![aula04_capa.png](./figuras/aula04_capa.png)

# Vamos estudar agora a sintaxe da linguagem Python

## 1.Comentários

In [16]:
# Comentário de uma única linha

# A variável a representa a temperatura de uma mistura no processo de produção de uma peça
a = 23.5


'''
Comentário de múltiplias linhas

O método a seguir recebe como parâmetros as variáveis a,b
Esse processa a soma de a e b dados como entrada
A saída é um número inteiro.
'''

'\nComentário de múltiplias linhas\n\nO método a seguir recebe como parâmetros as variáveis a,b\nEsse processa a soma de a e b dados como entrada\nA saída é um número inteiro.\n'

# 2.Input e Print
***

A função **input()** espera que o usuário digite alguma coisa para armazenar em alguma variável

A função **input()** sempre retorna uma string, se a gente quer que o usuário digite um número precisamos converter essas string para um tipo inteiro com a função **int()**

Para imprimir vários elementos em uma única linha usamos a função **split** para quebrar nos espaços em brancos ou virgula ou qualquer caractere definido na função. Depois só converter de string para o tipo certo da variável

In [19]:
# Usuário irá digitar o nome e o nome será armazenado na variável nome
nome = input("Insira seu nome:")
print(f"O nome digitado pelo usuário foi {nome}")

# Usuário irá digitar a idade e o valor será armazenado na variável age em forma número inteiro
idade = int(input("Insira sua idade:\n")) # coerção / casting explícito

# Usuário irá digitar a temperatura e o valor será armazenado na variável temperatura em forma número ponto flutuante
#(float)

temperatura = float(input("Informe a Temperatura"))

# Imprime o nome, a idade e o ano de nascimento da pessoa considerando estar em 2024
print(nome, "tem", idade, "anos e nasceu em", 2024-idade)

print(f"{nome} tem {idade} anos e a sua temperatura na chegada foi {temperatura}")

O nome digitado pelo usuário foi Hericson
Hericson tem 30 anos e nasceu em 1994
Hericson tem 30 anos e a sua temperatura na chegada foi 24.5


In [20]:
print(f"{nome} tem {idade} anos e nasceu em {2024-idade}")

Hericson tem 30 anos e nasceu em 1994


In [ ]:
data_science = 10

x = 0
y = 0
z = 0

x = y = z = 0

x = 10
x = 'oi'

# 3. Variáveis

O sinal de $=$ é um sinal de atribuição

Podemos criar quantas variáveis quiser

$x = y = z = 0$, todas as variaveis vão zerar

No python não precisa especificar o tipo de variável como em outras linguagens.

Python tudo é objeto

Em python o valor não é atribuido a variável, sim a variável é atribuido ao valor, já que tudo no python é objetos, a variável irá apontar para a referência do objeto na memória, logo o objeto é criado na memória e depois o variavel é atribuido a ele, podemos pensar nas variáveis como **Rótulos** que será atribuido a um valor, por exemplo, o objeto 23 vou inserir o rotulo idade nele, logo 23 tem um rótulo chamado idade, por isso python consegue atribuir rotulos a funções e etc...

```
idade = 23
imprimir = print
imprimir("Oi eu sou a função print!")
```

In [ ]:
# data_science_course (snake case)
# dataScienceCourse = (camel case)

método = 10


***
### 3.1 Regras de nomeclatura de variáveis
***

1. Não posso escrever nome da variável com espaço

2. Não posso usar caracteres especiais para criar variáveis, por exemplo ```#,!,,$,%,&,...```

3. Pode usar acentos e **ç** nas variáveis, porém não é uma boa prática

4. Crie variáveis e códigos sempre em ingles, boas práticas

5. Pode-se usar underline **_** no nome das variáveis, snake, boa prática, porém se quiser usar camelCase também pode

6. Não se pode nomear variáves com nomes chaves da linguagem, por exemplo, **class**, **while**, **for**...

7. Não use nomes como **int**, **float**, **print**, **sum** e etc... , não é uma boa prática

***
### 3.2 Tipos de Variáveis no Python
***

In [23]:
# Vamos criar o rótulo idade para o objeto 23 da classe int
idade = 23
# Vamos criar o rótulo temperatura para o objeto 36.5 da classe float
temperatura = 36.5
# Vamos criar o rótulo texto para o objeto "Boa noite" da classe str
texto = "Boa noite"
# Vamos criar o rótulo conectado para o objeto True da classe bool
conectado = True

print(type(23))
print(type(idade))
print(type(36.5))
print(type(temperatura))
print(type("Boa noite"))
print(type(texto))
print(type(True))
print(type(conectado))

<class 'int'>
<class 'int'>
<class 'float'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'bool'>
<class 'bool'>


In [24]:
# Vamos rotular a função print (Função como Rótulo)
imprimir = print
imprimir (f"Oi eu sou o print do número {100}")
print(type(imprimir))

imprimir("Boa noite!")

Oi eu sou o print do número 100
<class 'builtin_function_or_method'>
Boa noite!


In [27]:
imprimir('ciência de dados')

ciência de dados


In [5]:
# Vamos criar o rótulo list1 para o objeto da classe list
list1 = [1, 2, 3, 4]
print(list1)

[1, 2, 3, 4]


In [6]:
# Vamos criar um novo rotulo para o mesmo objeto da classe list
list2 = list1
print(list2)
print(list1)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [28]:
# Vamos modificar o valor da list2 e isso modificará o valor da list1 automaticamente
# Pois ambos os rótulos estão referenciando o mesmo objeto na memória
list2[0] = 10
print(list2)
print(list1)

[10, 2, 4, 4]
[10, 2, 3, 4]


In [29]:
# Para que isso não aconteça temos que fazer uma cópia do objeto
list2 = list1.copy()
list2[2] = 4
print(list1)
print(list2)

[10, 2, 3, 4]
[10, 2, 4, 4]


In [32]:
# Para strings temos a mesma ideia do acesso de elementos de uma lista
texto = "Boa noite"
print(f"Pegando o primeiro caracter do texto: {texto[0]}")

print(f"Pegando o último caracter do texto: {texto[-1]}")

print(f"Pegando o penúltimo caractere do texto: {texto[-2]}")



Pegando o primeiro caracter do texto: B
Pegando o último caracter do texto: e
Pegando o penúltimo caractere do texto: t


***
### 3.3 Comparações
***

Variáveis booleanas são variáveis que possuem dois valores constantes, **false** que significa falso e **true** que significa verdadeiro

Em binario ou linguagem de máquina são considerado os valores **1** para true e **0** para false

Usados para verificar se determinadas condições do meu programa são verdadeiras ou falsas

A função **bool()** pega um determinado valor passado como parâmetro e ele retorna se o valor é **True** ou **False**

Verdadeiro é todo valor que o python não considera como vazio, valores vazios são: **None**, **False**, **[]**, **{}**, **()**, **”**, , **0** e **0.0**

**Operadores de comparação**:

  - $<$: Menor
  - $>$: Maior
  - $<=$: Menor ou igual
  - $>=$: Maior ou igual
  - $==$: Igual
  - $!=$: Diferente

In [34]:
numero1 = int(input("Insira o primeiro número: "))
numero2 = int(input("Insira o segundo número: "))

testeMaior = numero1 > numero2
print(numero1, ">", numero2, ":", testeMaior)

print(numero1, "==", numero2, ":", numero1 == numero2)

print(numero1, "!=", numero2, ":", numero1 != numero2)

20 > 15 : True
20 == 15 : False
20 != 15 : True


***
### 3.4 Strings
***

String vem entre "aspas duplas" ou 'aspas simples'

Se for inserir uma string dentro de outra use string diferente por exemplo: "aspas duplas com 'aspas simples'" e vise versa

String é uma lista de caracteres: victor = 'v'+'i'+'c'+'t'+'o'+'r'

String é uma tupla, ela é imutavel, você não pode fazer: "Victor"[1] = 'a'

Quase tudo que faço com uma tupla consigo fazer com strings

In [37]:
# Concatenar strings
string1 = "Hoje irei ao "
string2 = "Curso"
print(string1 + string2)

print(f"{string1}{string2}")

# Para inserir um número em uma string use a função str(valor)
a = 3
print("Eu vi o aquele gol " + str(a) + " vezes")

# O len() devolve o número de caracteres que a frase possui
print(len("Victor"))

# Uma string pode considerar como o texto completo usando aspas triplas
minhaString = '''
Boa noite!

Gostaria de solicitar.......


Att,

'''

print(minhaString)

Hoje irei ao Curso
Hoje irei ao Curso
Eu vi o aquele gol 3 vezes
6

Boa noite!

Gostaria de solicitar.......


Att,




# 4. Estrutura de Dados

***
### 4.1 Listas
***

Para criar uma lista é só colocar a sequência de elementos entre colchetes []

A função print consegue imprimir uma lista

A lista pode misturar números inteiros, reais, strings, outras listas e etc

Indices negativos conta a lista de trás para frente, o indice 0 é o primeiro elemento da lista e o -1 é o ultimo elemento

**Técnica slice**: permite que você percorra elementos de uma lista criando outra lista a partir desses elementos

  - Se tentar percorrer uma lista na qual o $x > y$ retornará uma lista vazia
    
  - Duplo slice percorre de um elemento tal até um elemento tal com passos tal -> ```lista[::]```
    
  - Você pode atribuir o retorno do slice ou a sub-lista criada para uma variável

Para obter um elemento de uma lista dentro de outra é só achar o indice da lista interna e inserir o indice do elemento

Podemos somar duas lista, isso irá adicionar os elementos da segunda lista na primeira

Vale lembrar que a lista começa no 0

In [39]:
# Cria a lista
lista = [1, 2, 3, 4, 5]
nomes = []

print(lista)
print(nomes)

# Add elemento ao final da lista
nome = input("Digite um nome para ser adicionado na lista:\n")
nomes.append(nome)

nomes.append('Maria')

print(nomes)

[1, 2, 3, 4, 5]
[]
['José', 'Maria']


In [40]:
# "Soma" o primeiro e o segundo elemento da lista
print(lista[0]+lista[1])
print(nomes[0]+nomes[1])

3
JoséMaria


In [43]:
aplicativos = 'windows.exe.pdf' #Modificcar o '.' por um '_'ArithmeticError
aplicativos.replace('.', '_')

'windows_exe_pdf'

In [ ]:
# Funções sobre listas

# replace: é um método utilizado para substituir partes de uma string por outra.
print('Mississipi'.replace('ss', 'zz'))

frutas = []

frutas.insert(1, "uva")  # Insere "uva" na posição 1
print(frutas)

frutas = ["maçã", "banana"]
outras_frutas = ["laranja", "manga"]

frutas.extend(outras_frutas) # Junta as listas em uma só
print(frutas)

frutas = ["maçã", "banana", "laranja", "banana"]
frutas.remove("banana") # Remove a primeira ocorrência de um item na lista.
print(frutas)

frutas = ["maçã", "banana", "laranja"]
frutas.pop(1)  # Remove o item no índice 1 ('banana')
print(frutas)

# Sem índice, remove o último elemento
ultimo = frutas.pop()
print(ultimo)
print(frutas)

frutas = ["maçã", "banana", "laranja"]
indice = frutas.index("banana") # Retorna o índice da primeira ocorrência de um item na lista.
print(indice)

frutas = ["maçã", "banana", "laranja", "banana"]
contagem = frutas.count("banana") # Conta o número de ocorrências de um item na lista.
print(contagem)

frutas = ["maçã", "banana", "laranja"]
frutas.clear() # Remove todos os elementos da lista, deixando-a vazia.
print(frutas)

Mizzizzipi
['uva']
['maçã', 'banana', 'laranja', 'manga']
['maçã', 'laranja', 'banana']
['maçã', 'laranja']
laranja
['maçã']
1
2
[]


In [45]:
lista

[1, 2, 3, 4, 5]

In [46]:
# Percorre a lista do primeiro elemento até o terceiro
print(lista[0:3])

# Percorre a lista do primeiro elemento até o quarto de dois em dois
print(lista[0:4:2])

# Percorre do inicio da lista até o elemento 3
print(lista[:3])

# Percorre do elemento 3 até o final da lista
print(lista[3:])

[1, 2, 3]
[1, 3]
[1, 2, 3]
[4, 5]


In [51]:
# Cria a lista de listas
lista = [[[1,2],[3,4]],[5,6]]

# Imprime a lista de listas
print(lista)

# Imprime a lista com indice 0 dentro da lista com indice 0 dentro da lista principal
print(lista[0][0])

# Imprime o elemento dentro da lista com indice 0 ..
print(lista[0][0][0])

[[[1, 2], [3, 4]], [5, 6]]
[1, 2]
1


In [53]:
# Desempacotamento
x, y, z = [1, 2, 3]
print(x, y, z)

# Descartando o 3º elemento com _
x, y, _ = [1, 2, 3]
print(x, y)

1 2 3
1 2


***
### 4.2 Tuplas
***

Tuplas em Python são estruturas de dados semelhantes a listas, mas com uma diferença fundamental: são imutáveis. Isso significa que, uma vez criada, a tupla não pode ser alterada (não é possível adicionar, remover ou modificar elementos). Essa imutabilidade faz das tuplas uma escolha ideal para dados que não devem ser modificados, como coordenadas, configurações e dados constantes.

In [54]:
# Criando uma tupla
tupla = (1, 2, 3, 4)
print(tupla)

# Tupla sem parênteses
tupla = 5, 6, 7
print(tupla)

# Os elementos de uma tupla são acessados por índices, assim como em listas.
tupla = ('maçã', 'banana', 'laranja')
print(tupla[1])

# Tuplas são muito úteis para "desempacotar" valores em múltiplas variáveis de forma prática.
coordenadas = (10, 20)
x, y = coordenadas
print(x)
print(y)

# Concatenação
tupla1 = (1, 2, 3)
tupla2 = (4, 5)
tupla3 = tupla1 + tupla2
print(tupla3)

# Podemos repetir os elementos da tupla usando o operador *
tupla = ('a', 'b') * 3
print(tupla)  # Saída: ('a', 'b', 'a', 'b', 'a', 'b')

# Conta quantas vezes um valor específico aparece na tupla.
tupla = (1, 2, 2, 3, 2, 4)
print(tupla.count(2))

# Retorna o índice da primeira ocorrência de um valor específico.
tupla = (10, 20, 30, 40)
print(tupla.index(30))  # Saída: 2

(1, 2, 3, 4)
(5, 6, 7)
banana
10
20
(1, 2, 3, 4, 5)
('a', 'b', 'a', 'b', 'a', 'b')
3
2


***
### 4.3 Dicionários
***

Dicionario é uma lista com chave e valor, segue a mesma lógica dos dicionarios da vida real, temos um termo que é a chave e o seu significado que é o valor

In [56]:
# Inicializar um dicionario vazio
contato = {}

# Inizializar um dicionario com valores definidos
contato = {'nome': 'Pedro', 'telefone': 99283945, 'email': 'pedro@gmail.com'}

# Pegar o valor de uma determinada chave
print(contato['nome'])
print(contato['telefone'])
print(contato['email'])


# Adicionar/editar uma chave e valor dentro de um dicionario
contato['nova_chave'] = 'novo valor'
contato['nome'] = 'Pedro Morais'
print(contato)



# Dicionarios com parâmetros de tipos diferentes
pi = None

dictionary = {'name': 'Função tal',
              pi: 3.1416,
              'tuple_key': (1, 2, 3, 4),
              'contato': contato,
              'function': lambda x: x+1 #função anonima que simula f(x) = x + 1
             }

# Imprimir os valores inseridos dentro dessas chaves
print(dictionary['name'])
print(dictionary[pi])
print(dictionary['tuple_key'])
print(dictionary['contato'])
print(dictionary['function'] (10))

Pedro
99283945
pedro@gmail.com
{'nome': 'Pedro Morais', 'telefone': 99283945, 'email': 'pedro@gmail.com', 'nova_chave': 'novo valor'}
Função tal
3.1416
(1, 2, 3, 4)
{'nome': 'Pedro Morais', 'telefone': 99283945, 'email': 'pedro@gmail.com', 'nova_chave': 'novo valor'}
11


### 4.4 Usando Listas com dicionários

In [57]:
# Lista de dicionários, onde cada dicionário representa um aluno
alunos = [
    {"nome": "Alice", "idade": 20, "nota": 8.5},
    {"nome": "Bruno", "idade": 22, "nota": 7.0},
    {"nome": "Carla", "idade": 19, "nota": 9.0},
    {"nome": "Daniel", "idade": 21, "nota": 6.5}
]

print(alunos)

#Adicionando um Novo Dicionário (ALuno) à Lista
novo_aluno = {"nome": "Eduardo", "idade": 23, "nota": 7.5}
alunos.append(novo_aluno)
print(alunos)

#Removendo último Dicionário (ALuno) da Lista
alunos.pop()
print(alunos)

#Removendo primeiro Dicionário (ALuno) da Lista
alunos.pop(0)
print(alunos)


[{'nome': 'Alice', 'idade': 20, 'nota': 8.5}, {'nome': 'Bruno', 'idade': 22, 'nota': 7.0}, {'nome': 'Carla', 'idade': 19, 'nota': 9.0}, {'nome': 'Daniel', 'idade': 21, 'nota': 6.5}]
[{'nome': 'Alice', 'idade': 20, 'nota': 8.5}, {'nome': 'Bruno', 'idade': 22, 'nota': 7.0}, {'nome': 'Carla', 'idade': 19, 'nota': 9.0}, {'nome': 'Daniel', 'idade': 21, 'nota': 6.5}, {'nome': 'Eduardo', 'idade': 23, 'nota': 7.5}]
[{'nome': 'Alice', 'idade': 20, 'nota': 8.5}, {'nome': 'Bruno', 'idade': 22, 'nota': 7.0}, {'nome': 'Carla', 'idade': 19, 'nota': 9.0}, {'nome': 'Daniel', 'idade': 21, 'nota': 6.5}]
[{'nome': 'Bruno', 'idade': 22, 'nota': 7.0}, {'nome': 'Carla', 'idade': 19, 'nota': 9.0}, {'nome': 'Daniel', 'idade': 21, 'nota': 6.5}]


***
### 4.5 Sets (Conjuntos)
***

Conjuntos (ou sets) em Python são estruturas de dados que armazenam valores únicos e não ordenados. Eles são úteis para operações de conjuntos matemáticos como união, interseção e diferença, e também para remover duplicatas de uma coleção de dados.

Conjuntos suportam várias operações úteis, principalmente para comparações e filtragem de dados.

In [58]:
# Criando conjuntos
conjunto1 = {1, 2, 3, 4, 4 } # Elementos únicos
conjunto2 = set([3, 4, 5, 6])
print(conjunto1)
print(conjunto2)

# Adicionar: Podemos adicionar elementos com o método add().
conjunto = {1, 2, 3}
conjunto.add(4)
print(conjunto)

# Remover: Remover elementos com remove() (gera erro se o item não existe) ou discard() (não gera erro).
conjunto.remove(2)
print(conjunto)

conjunto.discard(5)  # Não gera erro, mesmo que 5 não esteja no conjunto

# União (| ou union()): Combina todos os elementos de dois conjuntos.
conjunto1 = {1, 2, 3}
conjunto2 = {3, 4, 5}
print(conjunto1 | conjunto2)

# Interseção (& ou intersection()): Retorna apenas os elementos presentes em ambos os conjuntos.
print(conjunto1 & conjunto2)

# Diferença (- ou difference()): Retorna os elementos que estão em um conjunto, mas não no outro.
print(conjunto1 - conjunto2)

# Diferença Simétrica (^ ou symmetric_difference()): Retorna os elementos que estão em um conjunto ou no outro, mas não em ambos.
print(conjunto1 ^ conjunto2)

# Subconjunto (issubset()): Verifica se um conjunto é subconjunto de outro (todos os elementos de um conjunto estão no outro).
conjunto_a = {1, 2}
conjunto_b = {1, 2, 3, 4}
print(conjunto_a.issubset(conjunto_b))


{1, 2, 3, 4}
{3, 4, 5, 6}
{1, 2, 3, 4}
{1, 3, 4}
{1, 2, 3, 4, 5}
{3}
{1, 2}
{1, 2, 4, 5}
True


***
### 4.6 Sets (Conjuntos) com Listas
***

In [59]:
# Remover Duplicatas de uma Lista:
lista = [1, 2, 2, 3, 4, 4, 5]
conjunto_unico = set(lista)
print(conjunto_unico)  # Saída: {1, 2, 3, 4, 5}

# Filtrar Elementos Comuns entre Listas:
lista1 = [1, 2, 3, 4]
lista2 = [3, 4, 5, 6]
comuns = set(lista1) & set(lista2)
print(comuns)

# Encontrar Elementos Exclusivos de Cada Conjunto:
conjunto1 = {1, 2, 3, 4}
conjunto2 = {3, 4, 5, 6}
exclusivos = conjunto1 ^ conjunto2
print(exclusivos)

{1, 2, 3, 4, 5}
{3, 4}
{1, 2, 5, 6}


# 5. Controle de Fluxo e Condicionais


O controle de fluxo e o uso de condicionais são fundamentais na programação em Python, pois permitem que o programa tome decisões e execute instruções de maneira dinâmica, com base em condições específicas. Essencialmente, essas estruturas dão "inteligência" ao código, permitindo que ele se adapte a diferentes cenários de execução.

***
### 5.1 Estruturas Condicionais (if, elif, else)
***

In [61]:
#Estrutura básica do comando if | elif | else

# verificar se um número é positivo, negativo ou zero:
numero = int(input("Digite um número: "))

if numero > 0:
    print(f"O número {numero} é positivo.")
elif numero < 0:
    print(f"O número {numero} é negativo.")
else:
    print("O número é zero.")

# Classificação de Idade

idade = int(input("Digite sua idade: "))

if idade < 12:
    print("Você é uma criança.")
elif idade < 18:
    print("Você é um adolescente.")
elif idade < 60:
    print("Você é um adulto.")
else:
    print("Você é um idoso.")


O número 10 é positivo.
Você é um adulto.


***
### 5.2 Estruturas de Repetição (for e while)
***

In [66]:
# Somar elementos de uma lista
numeros = [1, 2, 3, 4, 5]
soma = 0

for numero in numeros:
    soma += numero

print(f"A soma dos números é {soma}.")

#Exibir uma contagem regressiva

import time as time #biblioteca que trabalha com tempo

for i in range(5, -2, -1):
    print(i)
    time.sleep(1) # função que aguarda 1 seg para continuar a execução do código
print("Contagem regressiva concluída!")

A soma dos números é 15.
5
4
3
2
1
0
-1
Contagem regressiva concluída!


In [67]:
# Loop while para validar entrada do usuário
senha = "python123"
tentativa = ""

while tentativa != senha:
    tentativa = input("Digite a senha: ")
    if tentativa == senha:
        print("Acesso concedido!")
    else:
        print("Senha incorreta. Tente novamente.")

Senha incorreta. Tente novamente.
Senha incorreta. Tente novamente.
Acesso concedido!


In [69]:
#gerar um código para contar até 10 usando while

count = 0

while count < 10:
    count+=1 # count = count +1
    print(f"O contador é {count}")

O contador é 1
O contador é 2
O contador é 3
O contador é 4
O contador é 5
O contador é 6
O contador é 7
O contador é 8
O contador é 9
O contador é 10


In [70]:
# Loop while com condição de parada
contador = 0
while contador < 5:
    print("Contador:", contador)
    contador += 1

Contador: 0
Contador: 1
Contador: 2
Contador: 3
Contador: 4


In [71]:
# lista = [1,5,7,8,4,5,4,4,5,6,7,8,1,23,64,8,1,5,6,5]

range(10)

range(0, 10)

In [78]:
# Usando break e continue para controle avançado
for numero in range(10):
    if numero == 5:
        break  # Interrompe o loop quando numero for igual a 5
    print(numero)

print("\n")

for numero in range(10):
    if numero % 2 == 0:
        continue  # Pula números pares
    # print(numero)
    print(f'{numero} Não passei pelo continue')

0
1
2
3
4


1 Não passei pelo continue
3 Não passei pelo continue
5 Não passei pelo continue
7 Não passei pelo continue
9 Não passei pelo continue


# 6. Funções e Módulos

Função é alguma funcionalidade com nome bem definido que contém um trecho de código que você pode pedir para ele ser executado sempre que quiser, sem precisar rescrever o código


É como se fosse um bloco de código reutilizavel


* Como criar uma função:

```py
def nome_da_funcao(argumento01, argumento02, ...):
    # Código da função
    return alguma_coisa
```

* Declarar a função:

```py
alguma_coisa = nome_da_funcao(argumento01, argumento02)
```

O **def** declara que estaremos construindo uma função na qual temos o nome da função e seus argumentos que serão passados para função


O **return** é opcional caso sua função retorne algo, ela pode somente imprimir algo não precisando do return, as funções podem retornar vários valores de uma vez, retornando uma tupla ou valores unicos se atribuido para a mesma quantidade de variaveis que retornou


As funções devem ser definidas antes de ser executadas


Para sair de uma função em uma determinada ocasião você pode declarar o return sem nenhum retorno, só para sair da função


**Nomeclaturas**: Não de o nome da função para nome de variaveis

Um função pode ter **tipagem estática**:

```py
def nome_da_funcao(argumento01: tipo, argumento02: tipo, ...) -> tipo:
    # Código da função
    return alguma_coisa
```

In [84]:
# Define a função de operações matematicas e retorna duas operações:soma e multiplicação entre dois números
def math_operation(number1, number2):
    return number1+number2, number1*number2

def math_operation_new(number1, number2):
    values_dict = {'soma': number1+number2, 'mult': number1*number2}
    return values_dict

# Armazena os dois resultados das operações em uma tupla
result = math_operation(3, 3)

# Imprime os resultados em uma tupla
print(result[1])



9


In [87]:
result = math_operation_new(3, 3)
result['mult']

9

In [83]:
result[1]

9

In [88]:
def imprimir_na_tela(mensagem): # procedimento -> não há retorno para esse subalgoritmo
    print(mensagem)

imprimir_na_tela("Boa noite\n para os alunos e alunas")

Boa noite
 para os alunos e alunas


### 6.1 Escopo

Ao inserir uma variável dentro de uma função você está passando um copia dela para a função, tudo que você fizer na função não altera a variavel principal fora dela.

Essa copia é uma variável local da função, fora dela essa variável não existe, por isso normalmente retornamos ela e guardamos em alguma variável fora da função

Qualquer variável criada dentro da função será uma variável local da função

Se quisermos uma variável global que seja vista fora de qualquer função, independente se a variavel está definida antes ou depois da função temos que usar a tag global antes da variável, porém temos que definir a variável antes de declarar a função

É uma boa prática de programação sempre que tiver muitas funções criar uma função principal chamada main() e executar ela no final do arquivo

In [ ]:
# Valores que serão incrementados na função
x = 0
y = 0 

# Função de incremento passando x globalmente e y localmente
def increment(y):
    global x

    x += 1
    y += 1

# Incrementando o valor de x e y 4 vezes
increment(y)
increment(y)
increment(y)
increment(y)

# Imprimindo o x incrementado e o y não muda pois é uma variável local da função
print("x =", x)
print("y =", y)


x = 4
y = 0


### 6.2 Argumentos

No python podemos inserir vários argumentos em uma função sem saber o número de argumentos utilizando o operador * no argumento

```py
def soma(*args):
    # Implementação
    
soma(1,2,3,4,5,...)
```

Podemos também passar em forma de dicionario:

```py
def pessoas(**kwargs):
    for key in kwargs:
        print("%s" % kwargs[key], end=", ")
    
pessoas(p1="João", p2="Pedro", p3="Maria")
```


Com isso o python vai pegar todos os argumentos passados na função e transformar em uma tupla chamada numeros

Porém o *numeros tem que ser o ultimo argumento da função, por exemplo, não pode:

```py
# Não pode
def soma(*numeros, numero):
    # Implementação
```

Podemos deixar valores pré definidos no argumento da função caso o usuário não passe nada

```py
def media(p1, p2, p3, peso1 = 1, peso2 = 2, peso3 = 3):
    # Implementação
```

Os argumentos definidos também tem que ser no final, não pode ter uma argumento definido no meio dos argumentos não definidos

In [90]:
# Função que retorna o maior número da lista de números passados
def maior_numero(*numeros):
    maior = numeros[0]
    for numero in numeros:
        if numero > maior:
            maior = numero
    return maior

def maior_da_lista(lista_numeros):
    maior = lista_numeros[0]
    for numero in lista_numeros:
        if numero > maior:
            maior = numero
    return maior

def soma(*valores):
    soma_total = 0
    for valor in valores:
        soma_total = soma_total + valor
    return soma_total

In [91]:
print(maior_numero(1,2,5,4,7,8,10,4,5,6,1))
print(maior_da_lista([1,2,3,5,78,98,1]))
print(soma(1,2,3))

10
98
6


In [93]:
# Função que recebe um dicionario de dados
def pessoas(**kwargs):
    for key in kwargs:
        print(f'{kwargs[key]}', end=', ')

pessoas(p1="João", p2="Pedro", p3="Maria", p4="José", p10= "Jonas")

João, Pedro, Maria, José, Jonas, 

***
#### 6.2.1 Argumento somente posicionais ou nomeados
***

Obriga a pessoa a passar os argumentos da função somente posicionais, um exemplo é os coversores de tipo:

```
int("10")
float("24.3")
```

Eles não permitem que você passe parâmetros nomeados como abaixo:

```
int(x="10")
float(x="24.3")
```

Eles te obrigam a passar o argumento posicional.

A partir da versão 3.8 podemos criar funções com argumentos somente posicionais, é só passar o `/` nos argumentos, tudo que tiver antes da `/` será somente posicional.

Da mesma forma podemos fazer com parâmetros nomeados passando o `*` nos argumentos, tudo que tiver depois do `*` será obrigatoriamente parâmetro nomeado.

In [ ]:
def soma_posicional(x: int, y: int, /, z: int = 10, *, w: int) -> int:
    """
    Recebe dois argumentos posicionais do tipo inteiro e um argumento nomeado e retorna
    a soma desses valores.
    """
    return x + y + z + w

print(soma_posicional(10, 20, w=30))
print(soma_posicional(10, 20, w=10, z=30 ))
print(soma_posicional(10, 20, 30, w=40))

70
70
100


In [96]:
print(soma_posicional(10, 20, z=30, w=10)) # erro causado pelos argumentos x,y serem apenas posicionais

70


#### Exemplo em uma função bem conhecida

In [97]:
# Uma lista de dicionários(usuários)
usuarios = [
    {"nome": "Samuel", "idade": 10},
    {"nome": "Pedro", "idade": 33},
    {"nome": "Maria", "idade": 22},
    {"nome": "Junior", "idade": 11},
    {"nome": "Kaio", "idade": 15},
]

def get_idade(obj):
    return obj['idade']

# usuários ordenados pela idade (ascendente)
print(sorted(usuarios, key=get_idade))

# usuários ordenados pela idade (decrescente)
print(sorted(usuarios, key=get_idade, reverse=True))

[{'nome': 'Samuel', 'idade': 10}, {'nome': 'Junior', 'idade': 11}, {'nome': 'Kaio', 'idade': 15}, {'nome': 'Maria', 'idade': 22}, {'nome': 'Pedro', 'idade': 33}]
[{'nome': 'Pedro', 'idade': 33}, {'nome': 'Maria', 'idade': 22}, {'nome': 'Kaio', 'idade': 15}, {'nome': 'Junior', 'idade': 11}, {'nome': 'Samuel', 'idade': 10}]


### 6.3 Módulos

Um módulo em Python é um arquivo que contém definições e instruções em Python, como funções, classes e variáveis, que podem ser reutilizadas em outros códigos. Python possui uma biblioteca padrão rica com vários módulos integrados que facilitam o desenvolvimento.

In [98]:
import math

# Usando a função sqrt do módulo math
raiz_quadrada = math.sqrt(16)
print(raiz_quadrada)  # Saída: 4.0

#Nesse exemplo, o módulo math é importado, e suas funções são acessadas usando math.nome_da_funcao.
#Isso organiza o código e evita conflitos com funções de outros módulos.

4.0


In [99]:
# Podemos importar apenas funções específicas de um módulo usando from ... import.
# Isso permite que usemos as funções diretamente, sem precisar prefixar o nome do módulo.

from math import sqrt, pi

# Agora podemos usar sqrt e pi diretamente
raiz_quadrada = sqrt(25)
print(raiz_quadrada)  # Saída: 5.0
print(pi)             # Saída: 3.141592653589793

5.0
3.141592653589793


In [100]:
# Podemos renomear um módulo ou função no momento da importação, usando as.
# Isso é útil quando o nome do módulo é longo ou para evitar conflitos de nomes.

import numpy as np

# Agora podemos usar 'np' em vez de 'numpy'
array = np.array([1, 2, 3, 4])
print(array)

[1 2 3 4]


In [101]:
# Podemos importar todas as funções e variáveis de um módulo usando o asterisco *.
# Isso é feito com from nome_do_modulo import *.
# No entanto, esse método não é recomendado para projetos maiores, pois pode gerar
# conflitos de nome e prejudicar a legibilidade do código.

from math import *

print(sin(0))    # Saída: 0.0
print(cos(0))    # Saída: 1.0

0.0
1.0


In [ ]:
# Além dos módulos da biblioteca padrão, também podemos importar módulos criados pelo usuário.
# Por exemplo, se você tiver um arquivo meu_modulo.py com uma função chamada soma, poderá importá-lo em outro script:

# Função definida no módulo criado pelo usuário em um arquivo meu_modulo.py
def soma(a, b):
    return a + b

# código em outro arquivo outro_arquivo.py
import meu_modulo

resultado = meu_modulo.soma(5, 3)
print(resultado)  # Saída: 8


In [ ]:
# Para instalar e usar bibliotecas externas, usamos o pip, que é o gerenciador de pacotes padrão do Python.
# Por exemplo, para instalar a biblioteca requests:

pip install requests


In [ ]:
# Após a instalação, podemos importar e usar a biblioteca normalmente:
import requests

resposta = requests.get("https://api.github.com")
print(resposta.status_code)  # Saída: 200

# 7. Bibliotecas Básicas Pandas e Numpy

As bibliotecas pandas e numpy são fundamentais para a ciência de dados em Python. Elas oferecem funcionalidades essenciais para manipulação de dados e computação numérica, tornando o processamento de grandes volumes de dados mais eficiente e simplificado. Abaixo, veremos a importância de cada biblioteca e exemplos de uso organizados.

### 7.1 Pandas

pandas é uma biblioteca especializada em manipulação e análise de dados tabulares, como arquivos CSV e Excel. Ela fornece duas principais estruturas de dados: Series (para dados unidimensionais) e DataFrame (para dados bidimensionais), que facilitam o armazenamento, a manipulação e a análise de dados de maneira estruturada. Com pandas, podemos realizar operações complexas de filtragem, agregação e limpeza de dados com uma sintaxe intuitiva e eficiente.

In [102]:
# Criando um DataFrame a partir de um dicionário

import pandas as pd

#Dicionário com dados de um aluno(a)
dados = {
    "Nome": ["Alice", "Bruno", "Carla"],
    "Idade": [25, 30, 22],
    "Nota": [8.5, 7.2, 9.1]
}

df = pd.DataFrame(dados)
print(df)


# Criando Series individuais para cada coluna
nomes = pd.Series(["Alice", "Bruno", "Carla"])
idades = pd.Series([25, 30, 22])
notas = pd.Series([8.5, 7.2, 9.1])

# Criando um DataFrame a partir das Series
df_alunos = pd.DataFrame({
    "Nome": nomes,
    "Idade": idades,
    "Nota": notas
})

print(df_alunos)

print(nomes) # cada nome associado com indíce


    Nome  Idade  Nota
0  Alice     25   8.5
1  Bruno     30   7.2
2  Carla     22   9.1
    Nome  Idade  Nota
0  Alice     25   8.5
1  Bruno     30   7.2
2  Carla     22   9.1
0    Alice
1    Bruno
2    Carla
dtype: object


In [103]:
df_alunos

Nome  Idade  Nota
0  Alice     25   8.5
1  Bruno     30   7.2
2  Carla     22   9.1

In [ ]:
# Leitura de um arquivo CSV
df = pd.read_csv("datasets/dados_exemplo.csv")
print(df.head())  # Mostra as primeiras 5 linhas

In [107]:
mask_approved = df_alunos['Nota'] > 8

df_alunos[mask_approved]

Nome  Idade  Nota
0  Alice     25   8.5
2  Carla     22   9.1

In [ ]:
# Filtrar dados com base em uma condição, como selecionar alunos com nota maior que 8.

#dataframe com os dados filtrados
aprovados = df[df["Nota"] > 8]
print(aprovados)

In [108]:
# Agrupar por uma coluna e calcular a média das notas, por exemplo.

media_idade = df.groupby("Idade")["Nota"].mean()
print(media_idade)

Idade
22    9.1
25    8.5
30    7.2
Name: Nota, dtype: float64


In [109]:
#Preencher dados ausentes com valores específicos ou com a média da coluna.
# Eduarda recebeu uma nota a partir da média

df["Nota"].fillna(df["Nota"].mean(), inplace=True)

print(df)

    Nome  Idade  Nota
0  Alice     25   8.5
1  Bruno     30   7.2
2  Carla     22   9.1


In [110]:
# Obter uma visão geral rápida dos dados, como média, mediana e desvio padrão.
print(df.describe())

           Idade      Nota
count   3.000000  3.000000
mean   25.666667  8.266667
std     4.041452  0.971253
min    22.000000  7.200000
25%    23.500000  7.850000
50%    25.000000  8.500000
75%    27.500000  8.800000
max    30.000000  9.100000


### 7.2 Numpy

numpy é uma biblioteca para computação numérica em Python. Ela é otimizada para manipulação de arrays multidimensionais e permite realizar operações matemáticas e estatísticas de maneira muito eficiente. numpy é a base de outras bibliotecas de ciência de dados, incluindo pandas, que usa os arrays do numpy para armazenamento de dados.

In [111]:
# Criando um array unidimensional (vetor) e um array bidimensional (matriz).

import numpy as np

vetor = np.array([1, 2, 3, 4])
matriz = np.array([[1, 2], [3, 4]])
print(vetor)
print(matriz)

[1 2 3 4]
[[1 2]
 [3 4]]


In [112]:
# Realizar operações como soma, multiplicação e exponenciação em todos os elementos do array.

vetor = np.array([1, 2, 3, 4])
print(vetor + 2)        # Soma 2 a cada elemento
print(vetor * 3)        # Multiplica cada elemento por 3
print(np.sqrt(vetor))   # Raiz quadrada de cada elemento

[3 4 5 6]
[ 3  6  9 12]
[1.         1.41421356 1.73205081 2.        ]


In [113]:
# Cálculo de média, mediana, variância e desvio padrão de um array.

dados = np.array([1, 2, 3, 4, 5])
print("Média:", np.mean(dados))
print("Mediana:", np.median(dados))
print("Desvio Padrão:", np.std(dados))

Média: 3.0
Mediana: 3.0
Desvio Padrão: 1.4142135623730951


In [114]:
#Geração de dados aleatórios para simulações, como amostras normais ou uniformes.

aleatorios = np.random.rand(5)       # Array com 5 números aleatórios entre 0 e 1
normais = np.random.randn(5)         # Array com 5 números aleatórios de uma distribuição normal
print(aleatorios)
print(normais)

[0.43975364 0.36002841 0.0234164  0.24170746 0.21279201]
[ 0.2439147   0.51250456 -0.11433023 -0.08940991 -0.56542192]


In [115]:
# Manipulação de partes específicas de um array, semelhante ao uso de slices em listas.

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz[0, :])  # Primeira linha
print(matriz[:, 1])  # Segunda coluna

[1 2 3]
[2 5 8]


In [116]:
# Operações entre arrays de mesmo tamanho, elemento a elemento, e produto de matriz.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)               # Soma elemento a elemento
print(a * b)               # Multiplicação elemento a elemento
print(np.dot(a, b))        # Produto escalar entre vetores

[5 7 9]
[ 4 10 18]
32


### 7.3 Numpy & Pandas

pandas e numpy trabalham muito bem juntos. Por exemplo, podemos usar numpy para criar dados simulados e carregá-los em um DataFrame pandas para análise.

In [117]:
import numpy as np
import pandas as pd

# Criando dados simulados com numpy
idades = np.random.randint(18, 60, size=10)
notas = np.random.normal(loc=7.0, scale=1.5, size=10)

# Criando um DataFrame com pandas
df = pd.DataFrame({"Idade": idades, "Nota": notas})

# Calculando a média das notas e exibindo o DataFrame
print("Média das Notas:", np.mean(df["Nota"]))
print(df)

# Salvando o DataFrame em um arquivo CSV
df.to_csv("datasets/dados_simulados.csv", index=False)
print("Dados salvos em 'dados_simulados.csv'")

Média das Notas: 7.108652067104911
   Idade      Nota
0     25  7.297760
1     40  8.490898
2     31  7.110077
3     34  9.815991
4     58  7.910073
5     39  6.732021
6     54  3.754019
7     45  9.075538
8     40  8.246817
9     48  2.653327
Dados salvos em 'dados_simulados.csv'


In [118]:
df

Idade      Nota
0     25  7.297760
1     40  8.490898
2     31  7.110077
3     34  9.815991
4     58  7.910073
5     39  6.732021
6     54  3.754019
7     45  9.075538
8     40  8.246817
9     48  2.653327

### Resumo
- pandas: Focado na manipulação de dados estruturados e tabulares, permitindo leitura, limpeza e análise de dados.
- numpy: Focado em computação numérica com arrays e operações matemáticas rápidas e eficientes.

Juntas, essas bibliotecas são o alicerce para qualquer trabalho de análise e ciência de dados em Python, otimizando o processamento e análise de grandes volumes de dados.